title: Spectra Secondary School
url: https://spectra.edu.sg
favicon: /images/logo_full.png
colors:
  primary-color: "#3e006d"
  secondary-color: "#006b51"
  media-colors:
    - title: media-color-one
      color: "#3e006d"
    - title: media-color-two
      color: "#3e006d"
    - title: media-color-three
      color: "#006b51"
    - title: media-color-four
      color: "#006b51"
    - title: media-color-five
      color: "#006b51"
description: Spectra Secondary School Official Website
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d2vlyv0oi5rmi5.amplifyapp.com
prod: https://master.d2vlyv0oi5rmi5.amplifyapp.com
shareicon: /images/logo_full.png
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
google_analytics_ga4: ""
resources_name: latest-updates
